// AUTO-GENERATED — 마스터/서베이 기반 지점 소개·규모 (기준일 2026-09-09).
// intro=핵심특징 요약, size=평수, floor=층구성, opened=오픈시기.
export interface BranchFact { intro: string; size: number | null; floor: string; opened: string; }
export const BRANCH_FACTS: Record<string, BranchFact> = {
  "가락점": { intro: "지하 1~3층 규모의 헬스·필라테스 복합센터", size: 2000, floor: "지하", opened: "2021년 4월" },
  "신촌점": { intro: "사우나·수영·골프·스쿼시·기구필라테스까지 가능한 복합 스포츠형 센터", size: 2000, floor: "지하", opened: "2020년 10월" },
  "전주송천점": { intro: "전주사우나 결합형 대형 복합센터", size: 1400, floor: "지하/저층(1~3F)", opened: "2022년 11월" },
  "매탄점": { intro: "헬스·PT 중심", size: 350, floor: "지하", opened: "2022년 5월" },
  "판교역점": { intro: "헬스·PT 중심", size: 200, floor: "지하", opened: "2024년 5월" },
  "송촌점": { intro: "350평·수입 머신 60종, 사우나·기구필라테스·스피닝, 새벽 필라테스반", size: 600, floor: "고층(8F+)", opened: "2020년 10월" },
  "강남고속터미널점": { intro: "고속터미널 내 지상층, 헬스·4:1 기구필라테스·PT, 연중무휴", size: 400, floor: "저층(1~3F)", opened: "2021년 11월" },
  "건대스타시티몰점": { intro: "스타시티몰 입점, 스파·사우나·개별 샤워부스, 헬스·골프 레슨", size: 600, floor: "지하", opened: "" },
  "문정역점": { intro: "확인 필요 등급, 헬스·PT·필라테스 중심", size: null, floor: "지하", opened: "2025년 3월" },
  "여의도역점": { intro: "확인 필요 등급, 헬스·PT 중심", size: 500, floor: "", opened: "2021년 4월" },
  "잠실점": { intro: "롯데월드몰권 지하 연결, 명품 머신 약 96종, 최대 3시간 주차, 365일 운영", size: 330, floor: "중층(4~7F)", opened: "2020년 10월" },
  "광교점": { intro: "헬스·PT·필라테스 중심", size: null, floor: "지하", opened: "" },
  "권선점": { intro: "헬스·PT 중심", size: 300, floor: "저층(1~3F)", opened: "2021년 7월" },
  "망포점": { intro: "헬스·PT·필라테스 중심", size: null, floor: "", opened: "2024년 5월" },
  "미금점": { intro: "헬스·PT·필라테스 중심", size: 320, floor: "", opened: "2024년 1월" },
  "수내점": { intro: "수내동 야외 테라스존, 프리웨이트·기구·유산소·필라테스 컨디셔닝존, 365일 운영", size: 270, floor: "", opened: "2021년 12월" },
  "수지점": { intro: "헬스·PT·필라테스·골프 중심", size: null, floor: "지하", opened: "" },
  "인계점": { intro: "헬스·PT·필라테스·골프 중심", size: 1000, floor: "고층(8F+)", opened: "2020년 4월" },
  "정자점": { intro: "헬스·PT·필라테스·골프 중심", size: 350, floor: "저층(1~3F)", opened: "" },
  "천천점": { intro: "헬스·PT 중심", size: 250, floor: "", opened: "2024년 5월" },
  "롯데대구역점": { intro: "헬스·PT 중심", size: null, floor: "", opened: "2024년 11월" },
  "도안점": { intro: "500평대, 헬스·PT·필라테스, 평일 06~24시·주말 10~19시, 연중무휴", size: 500, floor: "중층(4~7F)", opened: "2023년 12월" },
  "태평점": { intro: "500평대, 헬스·PT·1:1/6:1 기구필라테스, 수입 머신·유산소존, 3시간 무료주차", size: 390, floor: "", opened: "2023년 1월" },
  "테크노밸리점": { intro: "헬스·PT 중심", size: 300, floor: "", opened: "2022년 5월" },
  "상암MBC점": { intro: "지상층 피트니스, 헬스·필라테스 동시 이용, 상암 업무지구 접근성", size: 300, floor: "저층(1~3F)", opened: "2021년 4월" },
  "선릉점": { intro: "600평 규모, 헬스·골프·4:1 필라테스 올인원, 건식 사우나·프라이빗 골프 타석·주차 지원", size: 500, floor: "지하/저층(1~3F)", opened: "2021년 12월" },
  "양천향교역점": { intro: "헬스·PT·골프 중심", size: 700, floor: "", opened: "2023년 11월" },
  "여의도점": { intro: "24시간 플레이스 등록, 헬스·필라테스, 대형 주차공간·안마의자·공기청정 편의시설", size: 250, floor: "지하", opened: "2019년 12월" },
  "영등포점": { intro: "헬스·필라테스, 물리치료사 출신 트레이너 상주, 필라테스룸 4개·개별 샤워부스·대형 주차", size: 300, floor: "지하", opened: "" },
  "홍대점": { intro: "24시간 플레이스 등록, 헬스·필라테스·1:1 PT, 홍대입구역 상권의 복합센터", size: 350, floor: "지하", opened: "2023년 1월" },
  "삼산점": { intro: "헬스·PT·골프 중심", size: 500, floor: "", opened: "2022년 10월" },
  "신부점": { intro: "헬스·PT 중심", size: 500, floor: "중층(4~7F)", opened: "2018년 2월" },
  "고양행신점": { intro: "헬스·PT·필라테스 중심", size: 350, floor: "", opened: "2023년 5월" },
  "배곧점": { intro: "헬스·PT·필라테스 중심", size: 400, floor: "", opened: "2023년 6월" },
  "병점점": { intro: "헬스·PT 중심", size: null, floor: "", opened: "2024년 9월" },
  "상록수역점": { intro: "헬스·PT 중심", size: 440, floor: "", opened: "2023년 3월" },
  "상현점": { intro: "헬스·PT 중심", size: 170, floor: "지하", opened: "2023년 2월" },
  "안산중앙점": { intro: "헬스·PT·필라테스 중심", size: 1000, floor: "", opened: "2023년 6월" },
  "영통판타지움점": { intro: "헬스·PT 중심", size: 150, floor: "중층(4~7F)", opened: "2024년 4월" },
  "일산주엽점": { intro: "롯데마트 입점 600평 규모, 헬스·PT·골프, GDR 포함 35타석", size: 576, floor: "", opened: "2023년 5월" },
  "죽전점": { intro: "헬스·PT·골프 중심", size: 280, floor: "", opened: "2024년 4월" },
  "NC대전유성점": { intro: "NC 유성점 10층, 헬스·PT·필라테스, 유성온천역 도보권·3시간 무료주차", size: 150, floor: "", opened: "2022년 10월" },
  "관저점": { intro: "헬스·PT·필라테스 중심", size: 500, floor: "", opened: "" },
  "대전터미널점": { intro: "헬스·PT 중심", size: 400, floor: "저층(1~3F)", opened: "2023년 3월" },
  "둔산점": { intro: "헬스·PT·필라테스 중심", size: 400, floor: "", opened: "2018년 12월" },
  "목원대점": { intro: "헬스·PT 중심", size: 150, floor: "중층(4~7F)", opened: "2024년 9월" },
  "월평점": { intro: "약 798㎡ 규모의 헬스·필라테스 센터, 정부청사역 도보권", size: 260, floor: "", opened: "2023년 7월" },
  "탄방점": { intro: "헬스·그룹필라테스·GX·줌바·점핑·에어로빅·요가를 결합한 그룹수업형 센터", size: 400, floor: "중층(4~7F)", opened: "2020년 1월" },
  "가산역점": { intro: "헬스·PT·골프 중심", size: 500, floor: "지하", opened: "2022년 8월" },
  "강남역점": { intro: "24시간·연중무휴, 헬스·PT·기구필라테스·플라잉요가, 수입 머신 약 90종, 사우나·개별 샤워부스, 자주식 주차", size: 500, floor: "지하", opened: "2021년 9월" },
  "당산역점": { intro: "당산역 12번 출구 인접, 헬스·필라테스 올인원, 필라룸 4개·월 300개 클래스, 여성 전용 스트레칭·힐링존", size: 250, floor: "지하", opened: "2022년 8월" },
  "문래역점": { intro: "헬스·PT 중심", size: 180, floor: "지하", opened: "2021년 3월" },
  "불광점": { intro: "불광역 초역세권, 300평대, 수입 머신 60여종, 5:1 기구필라테스, 2시간 무료주차", size: 250, floor: "지하", opened: "2023년 9월" },
  "서울시청점": { intro: "600평대, 헬스·필라테스, 수입 머신 50종·힙 머신 8종·천국의계단 4대, 2시간 무료주차", size: 500, floor: "지하", opened: "2022년 8월" },
  "신논현점": { intro: "헬스·PT·필라테스 중심", size: 300, floor: "지하", opened: "2022년 4월" },
  "을지로점": { intro: "4성급 호텔 내 입점, 헬스·3:1 필라테스·GDR 골프, KPGA 프로 레슨, 연중 운영", size: 380, floor: "지하/저층(1~3F)", opened: "2022년 5월" },
  "장안점": { intro: "800평 규모, 수입 머신 브랜드·천국의계단 4대·런닝머신 12대, 필라테스·GX·스피닝, 3시간 무료주차", size: 600, floor: "지하", opened: "" },
  "학동역점": { intro: "24시간·연중무휴, 헬스·필라테스 복합센터, 파나타 포함 수입 머신, 대형 주차장", size: 280, floor: "지하", opened: "2021년 11월" },
  "쌍용점": { intro: "헬스·PT·1:1 필라테스, 리모델링 호텔식 인테리어·3시간 무료주차·연중무휴", size: 200, floor: "", opened: "2016년 11월" },
  "비전점": { intro: "894평 대형센터, 헬스·필라테스·스크린골프·줌바·요가·스피닝, 해머스트렝스, 3시간 무료주차", size: 450, floor: "고층(8F+)", opened: "2019년 7월" },
  "철산점": { intro: "헬스·PT 중심", size: 300, floor: "", opened: "" },
  "창원중앙점": { intro: "헬스·PT·골프 중심", size: null, floor: "저층(1~3F)", opened: "" },
  "가오점": { intro: "300평대, 헬스·기구필라테스·1:1 PT, 평일 06~24시·주말 10~19시, 주차 지원", size: 390, floor: "고층(8F+)", opened: "2022년 12월" },
  "당리점": { intro: "헬스·PT·필라테스 중심", size: 500, floor: "저층(1~3F)", opened: "2024년 5월" },
  "하단점": { intro: "헬스·PT 중심", size: 200, floor: "", opened: "2021년 9월" },
  "가양역점": { intro: "헬스·PT 중심", size: 400, floor: "지하", opened: "2021년 12월" },
  "복대점": { intro: "헬스·PT·필라테스 중심", size: 350, floor: "", opened: "2020년 1월" },
};
export function getBranchFact(shortName: string): BranchFact | undefined { return BRANCH_FACTS[shortName]; }
